### ISSUE TITLE
Comment installe t'on ton script ? 

### ISSUE THREAD

**Issue by YohannsMonnier** [Zear06/LeekWars_Kikimeter#25]

**Comment by Foudge** [comment]
Sur Firefox il faut Greasemonkey : https://addons.mozilla.org/fr/firefox/addon/greasemonkey/
Sur Chrome il faut Tampermonkey : https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=fr
Sur les autres navigateur, je n'en sais rien.

Une fois l'extension installée, un double-clic sur le script permet de l'installer.

**Comment by YohannsMonnier** [comment]
Merci beaucoup !
